# -*- coding: utf-8 -*-
"""Sentiment-analyzer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KSOrRcRJvybwv7An73jirnOXMWw7y5KA
"""

import numpy as np
import math
import re
import pandas as pd
from bs4 import BeautifulSoup

from google.colab import drive

# Commented out IPython magic to ensure Python compatibility.
try:
#   %tensorflow_version 2.x
except Exception:
  pass
import tensorflow as tf

from tensorflow.keras import layers
import tensorflow_datasets as tfds

drive.mount("/content/drive")

cols = ['sentiment', 'id', 'date','query', 'user', 'text']
train_data = pd.read_csv(
    '/content/drive/MyDrive/trainingandtestdata/training.1600000.processed.noemoticon.csv',
    header=None, 
    names=cols, 
    engine='python', 
    encoding='latin1')

test_data = pd.read_csv(
    '/content/drive/MyDrive/trainingandtestdata/testdata.manual.2009.06.14.csv',
    header=None, 
    names=cols, 
    engine='python', 
    encoding='latin1')

data = train_data

data.head()

data.drop(['id', 'query', 'date', 'user'], axis=1, inplace=True)

def clean_tweet(tweet):
  tweet = BeautifulSoup(tweet, 'lxml').get_text()
  tweet = re.sub(r"@[A-Za-z0-9]+", " ", tweet)
  tweet = re.sub(r"https?://[A-Za-z0-9./]+", " ", tweet)
  tweet = re.sub(r" +", " ", tweet)
  return tweet

data_clean = [clean_tweet(tweet) for tweet in data.text]

data_labels = data.sentiment.values
data_labels[data_labels == 4] = 1

set(data_labels)

